plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-md

AllCops:
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
