module InfernoSuiteGenerator
  module Generator
    module GeneratorConfigKeeper
      module GeneratorConfigKeeperExtractors
        def multiple_and_expectation: (String profile_url, String resource_type, String param_id) -> ("SHALL" | "SHOULD" | "MAY" | nil)
        def multiple_or_expectation: (String profile_url, String resource_type, String param_id) -> ("SHALL" | "SHOULD" | "MAY" | nil)
        def override_search_expectation: (String profile_url, String resource_type, String param_id) -> ({ from: "SHALL" | "SHOULD" | "MAY", to: "SHALL" | "SHOULD" | "MAY" } | nil)
      end
    end
  end
end
