name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: RuboCop
        run: make docker-lint

  typecheck:
    name: Typechecking (Steep)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Steep check
        run: make docker-typecheck

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: make docker-tests
